language: node_js
node_js:
  - '9'
before_deploy:
  - "./scripts/prepare_release.sh && cd release"
deploy:
  - provider: script
    script: "cat ../coverage/lcov.info | ../node_modules/coveralls/bin/coveralls.js"
    skip_cleanup: true
    on:
      branches:
        only:
          - master
  - provider: npm
    email: u9520107@gmail.com
    skip_cleanup: true
    on:
      node: '9'
      tags: true
      condition: "$TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+"
      repo: u9520107/locale-loader
    api_key:
      secure: ml/dw677OT3HNj34WYeyG0cVVR0gzLAiPm2WzFZA0LPXR3xBPM6/JKxH2UPL9yRkIUE2eT58fIwLwmhX37oILINmhmn6sqDc6Wq/P8DIbWGJqospznaf0p94HuF0DWj/OWZ+D3u2/mXat+u8Cx8cBFMHfVnYlAge19ntO5u1GdBfIHQ0kVF5ktqnDFu2paJE02sR+6k/n+XBUQ3AN1H8vlS0jO4r//plvOhV5KpzJa7U2ujDzb9KDWiNHMNlj3fpZ9QetYPXvT0IpsF/ZU/q1B3MiCW89zftrjtC/DJDb7u0nNJlLfoa+s6CIVc2l4XCSHaT8+nPU2sMCSnQhqX6WiTU5AvMDFWZbvgrdJE5ReznX+2hh9s2YD8bkYludfYQagicsmFQMY4Cht8t9TNb+2oFbGRR3GG0UUwqQjcxTpTmGtKQ0vKZeSgjQHujKEb4BGulCLwLHtCMc8e7r7olHPG7oGTrfQ3l1oMLPRJlldtVy9PQGJ+FKlZVdQ9piZlcNMRczOi/2eKX+PQQrk6EqIKmLLS7/XFFF7cL2NXZQR7p16QsciedrvfjLhcRC7FJN/iTuq9kqgIYzm9mBWxaPtSAxN0+k9fn7irD3X58SspPfja2nSt2HyZH5zKApbCePI3AoTMLXxaEDnCSp8hrlflaYp6PqJV93Y+YsE68FSM=
